server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://metro.proxy.rlwy.net:44416/railway"
    username: "postgres"
    password: "edrDRqwWXGRQktsLQyoirbfDcpxhXcfI"
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB   # Giới hạn file tối đa 10MB
      max-request-size: 10MB  # Giới hạn tổng request tối đa 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

fptai:
  api:
    key: QKIh1IJzqbTmOmt4xaw120eP8c6M0TfN
    url: https://api.fpt.ai/vision/idr/vnm


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.htmlfs fdsfsdf

aws:
  region: us-east-1
  access-key: "AKIAZAI4GVIKCJPKKLVU"
  secret-key: "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"

cloudinary:
    cloud-name: "dpuekoyqz"
    api-key: "984166367576298"
    api-secret: "AF5MoSOUXN1uqUhMlTlBcobPJg0"

stress:
  extreme:
    threshold: 85
  high:
    threshold: 70
  moderate:
    threshold: 50
  mild:
    threshold: 30
  normal:
    threshold: 10
  confidence:
    threshold: 50