server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "admin"
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB   # Giới hạn file tối đa 10MB
      max-request-size: 10MB  # Giới hạn tổng request tối đa 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.htmlfs fdsfsdf

aws:
  region: us-east-1
  access-key: "AKIAZAI4GVIKCJPKKLVU"
  secret-key: "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"

cloudinary:
    cloud-name: "dfrlcr9ml"
    api-key: "659595431959666"
    api-secret: "23muN8vxgbbh8AHzXOvzj4HlSrg"

stress:
  extreme:
    threshold: 85
  high:
    threshold: 70
  moderate:
    threshold: 50
  mild:
    threshold: 30
  normal:
    threshold: 10
  confidence:
    threshold: 50