server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/test"
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 136913781813-nk8630l3fvt3bm32vrdsq4dbovres2bn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

#  data:
#    mongodb:
#      uri: "mongodb://localhost:27017/testdb"
#      username: nhattienn
#      password: ikH3qEIy9T0viObp
#     authentication-database: admin


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
