server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://metro.proxy.rlwy.net:36210/railway"
    username: "postgres"
    password: "VDBLyEwXPpnjNQCelXUNxFPREqQdWUKw"
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 465
    username: "nguyenletam026@gmail.com"
    password: "yfpx stun msoi binq"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Frontend URL for email verification links
app:
  frontend-url: "https://stresshelper.store"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

fptai:
  api:
    key: QKIh1IJzqbTmOmt4xaw120eP8c6M0TfN
    url: https://api.fpt.ai/vision/idr/vnm

# Refund System Configuration
refund:
  enabled: true
  doctor-response-timeout-minutes: 30
  auto-process-enabled: true
  scheduler:
    enabled: true
    interval-minutes: 15
  percentages:
    no-response: 100
    delayed-response: 50
    technical-issue: 100
    quality-issue: 75
    other: 50
  notifications:
    patient-enabled: true
    doctor-enabled: true
    admin-enabled: true
  doctor-warning-thresholds:
    mild: 3
    moderate: 5
    severe: 8


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

aws:  
  region: us-east-1
  access-key: "AKIAZAI4GVIKCJPKKLVU"
  secret-key: "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"

cloudinary:
    cloud-name: "dpuekoyqz"
    api-key: "984166367576298"
    api-secret: "AF5MoSOUXN1uqUhMlTlBcobPJg0"

stress:
  extreme:
    threshold: 85
  high:
    threshold: 70
  moderate:
    threshold: 50
  mild:
    threshold: 30
  normal:
    threshold: 10
  confidence:
    threshold: 50