server:
  port: 8080

spring:
    datasource:
      url: "jdbc:postgresql://localhost:5432/postgres"
      username: postgres
      password: admin

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html